//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp1.Assignment4Reference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentacar.org/", ConfigurationName="Assignment4Reference.WebServiceAssignment4Soap")]
    public interface WebServiceAssignment4Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllCars", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllPersons", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllPersons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllPersons", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllPersonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllOwners", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllOwners();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllOwners", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllOwnersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllCarsJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getAllCarsJava();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllCarsJava", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> getAllCarsJavaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllOwnerJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getAllOwnerJava();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllOwnerJava", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> getAllOwnerJavaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllPersonsJava", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string[] getAllPersonsJava();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/getAllPersonsJava", ReplyAction="*")]
        System.Threading.Tasks.Task<string[]> getAllPersonsJavaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAssignment4SoapChannel : DesktopApp1.Assignment4Reference.WebServiceAssignment4Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAssignment4SoapClient : System.ServiceModel.ClientBase<DesktopApp1.Assignment4Reference.WebServiceAssignment4Soap>, DesktopApp1.Assignment4Reference.WebServiceAssignment4Soap {
        
        public WebServiceAssignment4SoapClient() {
        }
        
        public WebServiceAssignment4SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAssignment4SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignment4SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignment4SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public System.Data.DataSet GetAllCars() {
            return base.Channel.GetAllCars();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllCarsAsync() {
            return base.Channel.GetAllCarsAsync();
        }
        
        public System.Data.DataSet GetAllPersons() {
            return base.Channel.GetAllPersons();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllPersonsAsync() {
            return base.Channel.GetAllPersonsAsync();
        }
        
        public System.Data.DataSet GetAllOwners() {
            return base.Channel.GetAllOwners();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllOwnersAsync() {
            return base.Channel.GetAllOwnersAsync();
        }
        
        public string[] getAllCarsJava() {
            return base.Channel.getAllCarsJava();
        }
        
        public System.Threading.Tasks.Task<string[]> getAllCarsJavaAsync() {
            return base.Channel.getAllCarsJavaAsync();
        }
        
        public string[] getAllOwnerJava() {
            return base.Channel.getAllOwnerJava();
        }
        
        public System.Threading.Tasks.Task<string[]> getAllOwnerJavaAsync() {
            return base.Channel.getAllOwnerJavaAsync();
        }
        
        public string[] getAllPersonsJava() {
            return base.Channel.getAllPersonsJava();
        }
        
        public System.Threading.Tasks.Task<string[]> getAllPersonsJavaAsync() {
            return base.Channel.getAllPersonsJavaAsync();
        }
    }
}
