//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="WebServiceAssignment4Soap", Namespace="http://rentacar.org/")]
public partial class WebServiceAssignment4 : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAllCarsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAllPersonsOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetAllOwnersOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllCarsJavaOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllOwnerJavaOperationCompleted;
    
    private System.Threading.SendOrPostCallback getAllPersonsJavaOperationCompleted;
    
    /// <remarks/>
    public WebServiceAssignment4() {
        this.Url = "http://localhost:49780/WebServiceAssignment4.asmx";
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event GetAllCarsCompletedEventHandler GetAllCarsCompleted;
    
    /// <remarks/>
    public event GetAllPersonsCompletedEventHandler GetAllPersonsCompleted;
    
    /// <remarks/>
    public event GetAllOwnersCompletedEventHandler GetAllOwnersCompleted;
    
    /// <remarks/>
    public event getAllCarsJavaCompletedEventHandler getAllCarsJavaCompleted;
    
    /// <remarks/>
    public event getAllOwnerJavaCompletedEventHandler getAllOwnerJavaCompleted;
    
    /// <remarks/>
    public event getAllPersonsJavaCompletedEventHandler getAllPersonsJavaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/HelloWorld", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld() {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginHelloWorld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("HelloWorld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndHelloWorld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync() {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState) {
        if ((this.HelloWorldOperationCompleted == null)) {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg) {
        if ((this.HelloWorldCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/GetAllCars", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetAllCars() {
        object[] results = this.Invoke("GetAllCars", new object[0]);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllCars(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAllCars", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetAllCars(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void GetAllCarsAsync() {
        this.GetAllCarsAsync(null);
    }
    
    /// <remarks/>
    public void GetAllCarsAsync(object userState) {
        if ((this.GetAllCarsOperationCompleted == null)) {
            this.GetAllCarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllCarsOperationCompleted);
        }
        this.InvokeAsync("GetAllCars", new object[0], this.GetAllCarsOperationCompleted, userState);
    }
    
    private void OnGetAllCarsOperationCompleted(object arg) {
        if ((this.GetAllCarsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAllCarsCompleted(this, new GetAllCarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/GetAllPersons", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetAllPersons() {
        object[] results = this.Invoke("GetAllPersons", new object[0]);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllPersons(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAllPersons", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetAllPersons(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void GetAllPersonsAsync() {
        this.GetAllPersonsAsync(null);
    }
    
    /// <remarks/>
    public void GetAllPersonsAsync(object userState) {
        if ((this.GetAllPersonsOperationCompleted == null)) {
            this.GetAllPersonsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllPersonsOperationCompleted);
        }
        this.InvokeAsync("GetAllPersons", new object[0], this.GetAllPersonsOperationCompleted, userState);
    }
    
    private void OnGetAllPersonsOperationCompleted(object arg) {
        if ((this.GetAllPersonsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAllPersonsCompleted(this, new GetAllPersonsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/GetAllOwners", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetAllOwners() {
        object[] results = this.Invoke("GetAllOwners", new object[0]);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetAllOwners(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetAllOwners", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetAllOwners(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public void GetAllOwnersAsync() {
        this.GetAllOwnersAsync(null);
    }
    
    /// <remarks/>
    public void GetAllOwnersAsync(object userState) {
        if ((this.GetAllOwnersOperationCompleted == null)) {
            this.GetAllOwnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllOwnersOperationCompleted);
        }
        this.InvokeAsync("GetAllOwners", new object[0], this.GetAllOwnersOperationCompleted, userState);
    }
    
    private void OnGetAllOwnersOperationCompleted(object arg) {
        if ((this.GetAllOwnersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetAllOwnersCompleted(this, new GetAllOwnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/getAllCarsJava", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] getAllCarsJava() {
        object[] results = this.Invoke("getAllCarsJava", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllCarsJava(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllCarsJava", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetAllCarsJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getAllCarsJavaAsync() {
        this.getAllCarsJavaAsync(null);
    }
    
    /// <remarks/>
    public void getAllCarsJavaAsync(object userState) {
        if ((this.getAllCarsJavaOperationCompleted == null)) {
            this.getAllCarsJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllCarsJavaOperationCompleted);
        }
        this.InvokeAsync("getAllCarsJava", new object[0], this.getAllCarsJavaOperationCompleted, userState);
    }
    
    private void OngetAllCarsJavaOperationCompleted(object arg) {
        if ((this.getAllCarsJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllCarsJavaCompleted(this, new getAllCarsJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/getAllOwnerJava", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] getAllOwnerJava() {
        object[] results = this.Invoke("getAllOwnerJava", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllOwnerJava(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllOwnerJava", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetAllOwnerJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getAllOwnerJavaAsync() {
        this.getAllOwnerJavaAsync(null);
    }
    
    /// <remarks/>
    public void getAllOwnerJavaAsync(object userState) {
        if ((this.getAllOwnerJavaOperationCompleted == null)) {
            this.getAllOwnerJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllOwnerJavaOperationCompleted);
        }
        this.InvokeAsync("getAllOwnerJava", new object[0], this.getAllOwnerJavaOperationCompleted, userState);
    }
    
    private void OngetAllOwnerJavaOperationCompleted(object arg) {
        if ((this.getAllOwnerJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllOwnerJavaCompleted(this, new getAllOwnerJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rentacar.org/getAllPersonsJava", RequestNamespace="http://rentacar.org/", ResponseNamespace="http://rentacar.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string[] getAllPersonsJava() {
        object[] results = this.Invoke("getAllPersonsJava", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetAllPersonsJava(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getAllPersonsJava", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndgetAllPersonsJava(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void getAllPersonsJavaAsync() {
        this.getAllPersonsJavaAsync(null);
    }
    
    /// <remarks/>
    public void getAllPersonsJavaAsync(object userState) {
        if ((this.getAllPersonsJavaOperationCompleted == null)) {
            this.getAllPersonsJavaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllPersonsJavaOperationCompleted);
        }
        this.InvokeAsync("getAllPersonsJava", new object[0], this.getAllPersonsJavaOperationCompleted, userState);
    }
    
    private void OngetAllPersonsJavaOperationCompleted(object arg) {
        if ((this.getAllPersonsJavaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getAllPersonsJavaCompleted(this, new getAllPersonsJavaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetAllCarsCompletedEventHandler(object sender, GetAllCarsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAllCarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAllCarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetAllPersonsCompletedEventHandler(object sender, GetAllPersonsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAllPersonsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAllPersonsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void GetAllOwnersCompletedEventHandler(object sender, GetAllOwnersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetAllOwnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetAllOwnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public System.Data.DataSet Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((System.Data.DataSet)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAllCarsJavaCompletedEventHandler(object sender, getAllCarsJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllCarsJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllCarsJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAllOwnerJavaCompletedEventHandler(object sender, getAllOwnerJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllOwnerJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllOwnerJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getAllPersonsJavaCompletedEventHandler(object sender, getAllPersonsJavaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getAllPersonsJavaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getAllPersonsJavaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}
