//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp1.Assignment5Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://rentacar.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string eMailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string no {
            get {
                return this.noField;
            }
            set {
                if ((object.ReferenceEquals(this.noField, value) != true)) {
                    this.noField = value;
                    this.RaisePropertyChanged("no");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobTitleField, value) != true)) {
                    this.jobTitleField = value;
                    this.RaisePropertyChanged("jobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eMail {
            get {
                return this.eMailField;
            }
            set {
                if ((object.ReferenceEquals(this.eMailField, value) != true)) {
                    this.eMailField = value;
                    this.RaisePropertyChanged("eMail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentacar.org/", ConfigurationName="Assignment5Reference.WebServiceAss5Soap")]
    public interface WebServiceAss5Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        DesktopApp1.Assignment5Reference.HelloWorldResponse HelloWorld(DesktopApp1.Assignment5Reference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.HelloWorldResponse> HelloWorldAsync(DesktopApp1.Assignment5Reference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/AddEmployee", ReplyAction="*")]
        DesktopApp1.Assignment5Reference.AddEmployeeResponse AddEmployee(DesktopApp1.Assignment5Reference.AddEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/AddEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.AddEmployeeResponse> AddEmployeeAsync(DesktopApp1.Assignment5Reference.AddEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/RemoveEmployee", ReplyAction="*")]
        DesktopApp1.Assignment5Reference.RemoveEmployeeResponse RemoveEmployee(DesktopApp1.Assignment5Reference.RemoveEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/RemoveEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.RemoveEmployeeResponse> RemoveEmployeeAsync(DesktopApp1.Assignment5Reference.RemoveEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/updateEmployee", ReplyAction="*")]
        DesktopApp1.Assignment5Reference.updateEmployeeResponse updateEmployee(DesktopApp1.Assignment5Reference.updateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/updateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.updateEmployeeResponse> updateEmployeeAsync(DesktopApp1.Assignment5Reference.updateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/searchEmployee", ReplyAction="*")]
        DesktopApp1.Assignment5Reference.searchEmployeeResponse searchEmployee(DesktopApp1.Assignment5Reference.searchEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/searchEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.searchEmployeeResponse> searchEmployeeAsync(DesktopApp1.Assignment5Reference.searchEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DesktopApp1.Assignment5Reference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DesktopApp1.Assignment5Reference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployee", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.AddEmployeeRequestBody Body;
        
        public AddEmployeeRequest() {
        }
        
        public AddEmployeeRequest(DesktopApp1.Assignment5Reference.AddEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class AddEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eMail;
        
        public AddEmployeeRequestBody() {
        }
        
        public AddEmployeeRequestBody(string no, string firstName, string lastName, string jobTitle, string eMail) {
            this.no = no;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.eMail = eMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddEmployeeResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.AddEmployeeResponseBody Body;
        
        public AddEmployeeResponse() {
        }
        
        public AddEmployeeResponse(DesktopApp1.Assignment5Reference.AddEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class AddEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddEmployeeResult;
        
        public AddEmployeeResponseBody() {
        }
        
        public AddEmployeeResponseBody(string AddEmployeeResult) {
            this.AddEmployeeResult = AddEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployee", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.RemoveEmployeeRequestBody Body;
        
        public RemoveEmployeeRequest() {
        }
        
        public RemoveEmployeeRequest(DesktopApp1.Assignment5Reference.RemoveEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class RemoveEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public RemoveEmployeeRequestBody() {
        }
        
        public RemoveEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveEmployeeResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.RemoveEmployeeResponseBody Body;
        
        public RemoveEmployeeResponse() {
        }
        
        public RemoveEmployeeResponse(DesktopApp1.Assignment5Reference.RemoveEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class RemoveEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveEmployeeResult;
        
        public RemoveEmployeeResponseBody() {
        }
        
        public RemoveEmployeeResponseBody(string RemoveEmployeeResult) {
            this.RemoveEmployeeResult = RemoveEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateEmployee", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.updateEmployeeRequestBody Body;
        
        public updateEmployeeRequest() {
        }
        
        public updateEmployeeRequest(DesktopApp1.Assignment5Reference.updateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class updateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string eMail;
        
        public updateEmployeeRequestBody() {
        }
        
        public updateEmployeeRequestBody(string no, string firstName, string lastName, string jobTitle, string eMail) {
            this.no = no;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.eMail = eMail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateEmployeeResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.updateEmployeeResponseBody Body;
        
        public updateEmployeeResponse() {
        }
        
        public updateEmployeeResponse(DesktopApp1.Assignment5Reference.updateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class updateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateEmployeeResult;
        
        public updateEmployeeResponseBody() {
        }
        
        public updateEmployeeResponseBody(string updateEmployeeResult) {
            this.updateEmployeeResult = updateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchEmployee", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.searchEmployeeRequestBody Body;
        
        public searchEmployeeRequest() {
        }
        
        public searchEmployeeRequest(DesktopApp1.Assignment5Reference.searchEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class searchEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public searchEmployeeRequestBody() {
        }
        
        public searchEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchEmployeeResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment5Reference.searchEmployeeResponseBody Body;
        
        public searchEmployeeResponse() {
        }
        
        public searchEmployeeResponse(DesktopApp1.Assignment5Reference.searchEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class searchEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DesktopApp1.Assignment5Reference.Employee searchEmployeeResult;
        
        public searchEmployeeResponseBody() {
        }
        
        public searchEmployeeResponseBody(DesktopApp1.Assignment5Reference.Employee searchEmployeeResult) {
            this.searchEmployeeResult = searchEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAss5SoapChannel : DesktopApp1.Assignment5Reference.WebServiceAss5Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAss5SoapClient : System.ServiceModel.ClientBase<DesktopApp1.Assignment5Reference.WebServiceAss5Soap>, DesktopApp1.Assignment5Reference.WebServiceAss5Soap {
        
        public WebServiceAss5SoapClient() {
        }
        
        public WebServiceAss5SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAss5SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAss5SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAss5SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment5Reference.HelloWorldResponse DesktopApp1.Assignment5Reference.WebServiceAss5Soap.HelloWorld(DesktopApp1.Assignment5Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DesktopApp1.Assignment5Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment5Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.HelloWorldRequestBody();
            DesktopApp1.Assignment5Reference.HelloWorldResponse retVal = ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.HelloWorldResponse> DesktopApp1.Assignment5Reference.WebServiceAss5Soap.HelloWorldAsync(DesktopApp1.Assignment5Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.HelloWorldResponse> HelloWorldAsync() {
            DesktopApp1.Assignment5Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment5Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.HelloWorldRequestBody();
            return ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment5Reference.AddEmployeeResponse DesktopApp1.Assignment5Reference.WebServiceAss5Soap.AddEmployee(DesktopApp1.Assignment5Reference.AddEmployeeRequest request) {
            return base.Channel.AddEmployee(request);
        }
        
        public string AddEmployee(string no, string firstName, string lastName, string jobTitle, string eMail) {
            DesktopApp1.Assignment5Reference.AddEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.AddEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.AddEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.eMail = eMail;
            DesktopApp1.Assignment5Reference.AddEmployeeResponse retVal = ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).AddEmployee(inValue);
            return retVal.Body.AddEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.AddEmployeeResponse> DesktopApp1.Assignment5Reference.WebServiceAss5Soap.AddEmployeeAsync(DesktopApp1.Assignment5Reference.AddEmployeeRequest request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.AddEmployeeResponse> AddEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string eMail) {
            DesktopApp1.Assignment5Reference.AddEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.AddEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.AddEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.eMail = eMail;
            return ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment5Reference.RemoveEmployeeResponse DesktopApp1.Assignment5Reference.WebServiceAss5Soap.RemoveEmployee(DesktopApp1.Assignment5Reference.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployee(request);
        }
        
        public string RemoveEmployee(string no) {
            DesktopApp1.Assignment5Reference.RemoveEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.RemoveEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.RemoveEmployeeRequestBody();
            inValue.Body.no = no;
            DesktopApp1.Assignment5Reference.RemoveEmployeeResponse retVal = ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).RemoveEmployee(inValue);
            return retVal.Body.RemoveEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.RemoveEmployeeResponse> DesktopApp1.Assignment5Reference.WebServiceAss5Soap.RemoveEmployeeAsync(DesktopApp1.Assignment5Reference.RemoveEmployeeRequest request) {
            return base.Channel.RemoveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.RemoveEmployeeResponse> RemoveEmployeeAsync(string no) {
            DesktopApp1.Assignment5Reference.RemoveEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.RemoveEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.RemoveEmployeeRequestBody();
            inValue.Body.no = no;
            return ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).RemoveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment5Reference.updateEmployeeResponse DesktopApp1.Assignment5Reference.WebServiceAss5Soap.updateEmployee(DesktopApp1.Assignment5Reference.updateEmployeeRequest request) {
            return base.Channel.updateEmployee(request);
        }
        
        public string updateEmployee(string no, string firstName, string lastName, string jobTitle, string eMail) {
            DesktopApp1.Assignment5Reference.updateEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.updateEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.updateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.eMail = eMail;
            DesktopApp1.Assignment5Reference.updateEmployeeResponse retVal = ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).updateEmployee(inValue);
            return retVal.Body.updateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.updateEmployeeResponse> DesktopApp1.Assignment5Reference.WebServiceAss5Soap.updateEmployeeAsync(DesktopApp1.Assignment5Reference.updateEmployeeRequest request) {
            return base.Channel.updateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.updateEmployeeResponse> updateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string eMail) {
            DesktopApp1.Assignment5Reference.updateEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.updateEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.updateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.eMail = eMail;
            return ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).updateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment5Reference.searchEmployeeResponse DesktopApp1.Assignment5Reference.WebServiceAss5Soap.searchEmployee(DesktopApp1.Assignment5Reference.searchEmployeeRequest request) {
            return base.Channel.searchEmployee(request);
        }
        
        public DesktopApp1.Assignment5Reference.Employee searchEmployee(string no) {
            DesktopApp1.Assignment5Reference.searchEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.searchEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.searchEmployeeRequestBody();
            inValue.Body.no = no;
            DesktopApp1.Assignment5Reference.searchEmployeeResponse retVal = ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).searchEmployee(inValue);
            return retVal.Body.searchEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.searchEmployeeResponse> DesktopApp1.Assignment5Reference.WebServiceAss5Soap.searchEmployeeAsync(DesktopApp1.Assignment5Reference.searchEmployeeRequest request) {
            return base.Channel.searchEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment5Reference.searchEmployeeResponse> searchEmployeeAsync(string no) {
            DesktopApp1.Assignment5Reference.searchEmployeeRequest inValue = new DesktopApp1.Assignment5Reference.searchEmployeeRequest();
            inValue.Body = new DesktopApp1.Assignment5Reference.searchEmployeeRequestBody();
            inValue.Body.no = no;
            return ((DesktopApp1.Assignment5Reference.WebServiceAss5Soap)(this)).searchEmployeeAsync(inValue);
        }
    }
}
