//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp1.Assignment3Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentacar.org/", ConfigurationName="Assignment3Reference.WebService3Soap")]
    public interface WebService3Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        DesktopApp1.Assignment3Reference.HelloWorldResponse HelloWorld(DesktopApp1.Assignment3Reference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.HelloWorldResponse> HelloWorldAsync(DesktopApp1.Assignment3Reference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name rentacar from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/rentacar", ReplyAction="*")]
        DesktopApp1.Assignment3Reference.rentacarResponse rentacar(DesktopApp1.Assignment3Reference.rentacarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/rentacar", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.rentacarResponse> rentacarAsync(DesktopApp1.Assignment3Reference.rentacarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment3Reference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DesktopApp1.Assignment3Reference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment3Reference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DesktopApp1.Assignment3Reference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rentacarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rentacar", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment3Reference.rentacarRequestBody Body;
        
        public rentacarRequest() {
        }
        
        public rentacarRequest(DesktopApp1.Assignment3Reference.rentacarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class rentacarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rentacar;
        
        public rentacarRequestBody() {
        }
        
        public rentacarRequestBody(string rentacar) {
            this.rentacar = rentacar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rentacarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="rentacarResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment3Reference.rentacarResponseBody Body;
        
        public rentacarResponse() {
        }
        
        public rentacarResponse(DesktopApp1.Assignment3Reference.rentacarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class rentacarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rentacarResult;
        
        public rentacarResponseBody() {
        }
        
        public rentacarResponseBody(string rentacarResult) {
            this.rentacarResult = rentacarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService3SoapChannel : DesktopApp1.Assignment3Reference.WebService3Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService3SoapClient : System.ServiceModel.ClientBase<DesktopApp1.Assignment3Reference.WebService3Soap>, DesktopApp1.Assignment3Reference.WebService3Soap {
        
        public WebService3SoapClient() {
        }
        
        public WebService3SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService3SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment3Reference.HelloWorldResponse DesktopApp1.Assignment3Reference.WebService3Soap.HelloWorld(DesktopApp1.Assignment3Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DesktopApp1.Assignment3Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment3Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment3Reference.HelloWorldRequestBody();
            DesktopApp1.Assignment3Reference.HelloWorldResponse retVal = ((DesktopApp1.Assignment3Reference.WebService3Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.HelloWorldResponse> DesktopApp1.Assignment3Reference.WebService3Soap.HelloWorldAsync(DesktopApp1.Assignment3Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.HelloWorldResponse> HelloWorldAsync() {
            DesktopApp1.Assignment3Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment3Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment3Reference.HelloWorldRequestBody();
            return ((DesktopApp1.Assignment3Reference.WebService3Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment3Reference.rentacarResponse DesktopApp1.Assignment3Reference.WebService3Soap.rentacar(DesktopApp1.Assignment3Reference.rentacarRequest request) {
            return base.Channel.rentacar(request);
        }
        
        public string rentacar(string rentacar1) {
            DesktopApp1.Assignment3Reference.rentacarRequest inValue = new DesktopApp1.Assignment3Reference.rentacarRequest();
            inValue.Body = new DesktopApp1.Assignment3Reference.rentacarRequestBody();
            inValue.Body.rentacar = rentacar1;
            DesktopApp1.Assignment3Reference.rentacarResponse retVal = ((DesktopApp1.Assignment3Reference.WebService3Soap)(this)).rentacar(inValue);
            return retVal.Body.rentacarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.rentacarResponse> DesktopApp1.Assignment3Reference.WebService3Soap.rentacarAsync(DesktopApp1.Assignment3Reference.rentacarRequest request) {
            return base.Channel.rentacarAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment3Reference.rentacarResponse> rentacarAsync(string rentacar) {
            DesktopApp1.Assignment3Reference.rentacarRequest inValue = new DesktopApp1.Assignment3Reference.rentacarRequest();
            inValue.Body = new DesktopApp1.Assignment3Reference.rentacarRequestBody();
            inValue.Body.rentacar = rentacar;
            return ((DesktopApp1.Assignment3Reference.WebService3Soap)(this)).rentacarAsync(inValue);
        }
    }
}
