//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApp1.Assignment6Reference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://rentacar.org/", ConfigurationName="Assignment6Reference.WebServiceAss6Soap")]
    public interface WebServiceAss6Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.HelloWorldResponse HelloWorld(DesktopApp1.Assignment6Reference.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.HelloWorldResponse> HelloWorldAsync(DesktopApp1.Assignment6Reference.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllIndexesResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllIndexes", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllIndexesResponse GetAllIndexes(DesktopApp1.Assignment6Reference.GetAllIndexesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllIndexesResponse> GetAllIndexesAsync(DesktopApp1.Assignment6Reference.GetAllIndexesRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllKeysResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllKeys", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllKeysResponse GetAllKeys(DesktopApp1.Assignment6Reference.GetAllKeysRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllKeysResponse> GetAllKeysAsync(DesktopApp1.Assignment6Reference.GetAllKeysRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllTableConstraintsResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTableConstraints", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse GetAllTableConstraints(DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTableConstraints", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse> GetAllTableConstraintsAsync(DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllColumnsFromEmp1Result from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllColumnsFromEmp1", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response GetAllColumnsFromEmp1(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllColumnsFromEmp1", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response> GetAllColumnsFromEmp1Async(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request request);
        
        // CODEGEN: Generating message contract since element name GetAllColumnsFromEmp2Result from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllColumnsFromEmp2", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response GetAllColumnsFromEmp2(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllColumnsFromEmp2", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response> GetAllColumnsFromEmp2Async(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesDB1Result from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTablesDB1", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllTablesDB1Response GetAllTablesDB1(DesktopApp1.Assignment6Reference.GetAllTablesDB1Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTablesDB1", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB1Response> GetAllTablesDB1Async(DesktopApp1.Assignment6Reference.GetAllTablesDB1Request request);
        
        // CODEGEN: Generating message contract since element name GetAllTablesDB2Result from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTablesDB2", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetAllTablesDB2Response GetAllTablesDB2(DesktopApp1.Assignment6Reference.GetAllTablesDB2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetAllTablesDB2", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB2Response> GetAllTablesDB2Async(DesktopApp1.Assignment6Reference.GetAllTablesDB2Request request);
        
        // CODEGEN: Generating message contract since element name GetNameAbsentMostResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetNameAbsentMost", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse GetNameAbsentMost(DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetNameAbsentMost", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse> GetNameAbsentMostAsync(DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest request);
        
        // CODEGEN: Generating message contract since element name GetInfoEmpSickness2004Result from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetInfoEmpSickness2004", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response GetInfoEmpSickness2004(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetInfoEmpSickness2004", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response> GetInfoEmpSickness2004Async(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request request);
        
        // CODEGEN: Generating message contract since element name GetInfoFromEmpAndRelativesResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetInfoFromEmpAndRelatives", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse GetInfoFromEmpAndRelatives(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetInfoFromEmpAndRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse> GetInfoFromEmpAndRelativesAsync(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest request);
        
        // CODEGEN: Generating message contract since element name GetMetaDataFromEmpAndRelatedResult from namespace http://rentacar.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetMetaDataFromEmpAndRelated", ReplyAction="*")]
        DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse GetMetaDataFromEmpAndRelated(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://rentacar.org/GetMetaDataFromEmpAndRelated", ReplyAction="*")]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse> GetMetaDataFromEmpAndRelatedAsync(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DesktopApp1.Assignment6Reference.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DesktopApp1.Assignment6Reference.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexes", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllIndexesRequestBody Body;
        
        public GetAllIndexesRequest() {
        }
        
        public GetAllIndexesRequest(DesktopApp1.Assignment6Reference.GetAllIndexesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllIndexesRequestBody {
        
        public GetAllIndexesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllIndexesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllIndexesResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllIndexesResponseBody Body;
        
        public GetAllIndexesResponse() {
        }
        
        public GetAllIndexesResponse(DesktopApp1.Assignment6Reference.GetAllIndexesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllIndexesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllIndexesResult;
        
        public GetAllIndexesResponseBody() {
        }
        
        public GetAllIndexesResponseBody(string GetAllIndexesResult) {
            this.GetAllIndexesResult = GetAllIndexesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeys", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllKeysRequestBody Body;
        
        public GetAllKeysRequest() {
        }
        
        public GetAllKeysRequest(DesktopApp1.Assignment6Reference.GetAllKeysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllKeysRequestBody {
        
        public GetAllKeysRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllKeysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllKeysResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllKeysResponseBody Body;
        
        public GetAllKeysResponse() {
        }
        
        public GetAllKeysResponse(DesktopApp1.Assignment6Reference.GetAllKeysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllKeysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllKeysResult;
        
        public GetAllKeysResponseBody() {
        }
        
        public GetAllKeysResponseBody(string GetAllKeysResult) {
            this.GetAllKeysResult = GetAllKeysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTableConstraintsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTableConstraints", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequestBody Body;
        
        public GetAllTableConstraintsRequest() {
        }
        
        public GetAllTableConstraintsRequest(DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTableConstraintsRequestBody {
        
        public GetAllTableConstraintsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTableConstraintsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTableConstraintsResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponseBody Body;
        
        public GetAllTableConstraintsResponse() {
        }
        
        public GetAllTableConstraintsResponse(DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllTableConstraintsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTableConstraintsResult;
        
        public GetAllTableConstraintsResponseBody() {
        }
        
        public GetAllTableConstraintsResponseBody(string GetAllTableConstraintsResult) {
            this.GetAllTableConstraintsResult = GetAllTableConstraintsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsFromEmp1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsFromEmp1", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1RequestBody Body;
        
        public GetAllColumnsFromEmp1Request() {
        }
        
        public GetAllColumnsFromEmp1Request(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllColumnsFromEmp1RequestBody {
        
        public GetAllColumnsFromEmp1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsFromEmp1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsFromEmp1Response", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1ResponseBody Body;
        
        public GetAllColumnsFromEmp1Response() {
        }
        
        public GetAllColumnsFromEmp1Response(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllColumnsFromEmp1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllColumnsFromEmp1Result;
        
        public GetAllColumnsFromEmp1ResponseBody() {
        }
        
        public GetAllColumnsFromEmp1ResponseBody(string GetAllColumnsFromEmp1Result) {
            this.GetAllColumnsFromEmp1Result = GetAllColumnsFromEmp1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsFromEmp2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsFromEmp2", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2RequestBody Body;
        
        public GetAllColumnsFromEmp2Request() {
        }
        
        public GetAllColumnsFromEmp2Request(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllColumnsFromEmp2RequestBody {
        
        public GetAllColumnsFromEmp2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllColumnsFromEmp2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllColumnsFromEmp2Response", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2ResponseBody Body;
        
        public GetAllColumnsFromEmp2Response() {
        }
        
        public GetAllColumnsFromEmp2Response(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllColumnsFromEmp2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllColumnsFromEmp2Result;
        
        public GetAllColumnsFromEmp2ResponseBody() {
        }
        
        public GetAllColumnsFromEmp2ResponseBody(string GetAllColumnsFromEmp2Result) {
            this.GetAllColumnsFromEmp2Result = GetAllColumnsFromEmp2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesDB1Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesDB1", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTablesDB1RequestBody Body;
        
        public GetAllTablesDB1Request() {
        }
        
        public GetAllTablesDB1Request(DesktopApp1.Assignment6Reference.GetAllTablesDB1RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesDB1RequestBody {
        
        public GetAllTablesDB1RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesDB1Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesDB1Response", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTablesDB1ResponseBody Body;
        
        public GetAllTablesDB1Response() {
        }
        
        public GetAllTablesDB1Response(DesktopApp1.Assignment6Reference.GetAllTablesDB1ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllTablesDB1ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTablesDB1Result;
        
        public GetAllTablesDB1ResponseBody() {
        }
        
        public GetAllTablesDB1ResponseBody(string GetAllTablesDB1Result) {
            this.GetAllTablesDB1Result = GetAllTablesDB1Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesDB2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesDB2", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTablesDB2RequestBody Body;
        
        public GetAllTablesDB2Request() {
        }
        
        public GetAllTablesDB2Request(DesktopApp1.Assignment6Reference.GetAllTablesDB2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTablesDB2RequestBody {
        
        public GetAllTablesDB2RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTablesDB2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTablesDB2Response", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetAllTablesDB2ResponseBody Body;
        
        public GetAllTablesDB2Response() {
        }
        
        public GetAllTablesDB2Response(DesktopApp1.Assignment6Reference.GetAllTablesDB2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetAllTablesDB2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllTablesDB2Result;
        
        public GetAllTablesDB2ResponseBody() {
        }
        
        public GetAllTablesDB2ResponseBody(string GetAllTablesDB2Result) {
            this.GetAllTablesDB2Result = GetAllTablesDB2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameAbsentMostRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameAbsentMost", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetNameAbsentMostRequestBody Body;
        
        public GetNameAbsentMostRequest() {
        }
        
        public GetNameAbsentMostRequest(DesktopApp1.Assignment6Reference.GetNameAbsentMostRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNameAbsentMostRequestBody {
        
        public GetNameAbsentMostRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNameAbsentMostResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNameAbsentMostResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetNameAbsentMostResponseBody Body;
        
        public GetNameAbsentMostResponse() {
        }
        
        public GetNameAbsentMostResponse(DesktopApp1.Assignment6Reference.GetNameAbsentMostResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetNameAbsentMostResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNameAbsentMostResult;
        
        public GetNameAbsentMostResponseBody() {
        }
        
        public GetNameAbsentMostResponseBody(string GetNameAbsentMostResult) {
            this.GetNameAbsentMostResult = GetNameAbsentMostResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEmpSickness2004Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEmpSickness2004", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004RequestBody Body;
        
        public GetInfoEmpSickness2004Request() {
        }
        
        public GetInfoEmpSickness2004Request(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoEmpSickness2004RequestBody {
        
        public GetInfoEmpSickness2004RequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoEmpSickness2004Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoEmpSickness2004Response", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004ResponseBody Body;
        
        public GetInfoEmpSickness2004Response() {
        }
        
        public GetInfoEmpSickness2004Response(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetInfoEmpSickness2004ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoEmpSickness2004Result;
        
        public GetInfoEmpSickness2004ResponseBody() {
        }
        
        public GetInfoEmpSickness2004ResponseBody(string GetInfoEmpSickness2004Result) {
            this.GetInfoEmpSickness2004Result = GetInfoEmpSickness2004Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoFromEmpAndRelativesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoFromEmpAndRelatives", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequestBody Body;
        
        public GetInfoFromEmpAndRelativesRequest() {
        }
        
        public GetInfoFromEmpAndRelativesRequest(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInfoFromEmpAndRelativesRequestBody {
        
        public GetInfoFromEmpAndRelativesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoFromEmpAndRelativesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoFromEmpAndRelativesResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponseBody Body;
        
        public GetInfoFromEmpAndRelativesResponse() {
        }
        
        public GetInfoFromEmpAndRelativesResponse(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetInfoFromEmpAndRelativesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInfoFromEmpAndRelativesResult;
        
        public GetInfoFromEmpAndRelativesResponseBody() {
        }
        
        public GetInfoFromEmpAndRelativesResponseBody(string GetInfoFromEmpAndRelativesResult) {
            this.GetInfoFromEmpAndRelativesResult = GetInfoFromEmpAndRelativesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetaDataFromEmpAndRelatedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetaDataFromEmpAndRelated", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequestBody Body;
        
        public GetMetaDataFromEmpAndRelatedRequest() {
        }
        
        public GetMetaDataFromEmpAndRelatedRequest(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetMetaDataFromEmpAndRelatedRequestBody {
        
        public GetMetaDataFromEmpAndRelatedRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMetaDataFromEmpAndRelatedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMetaDataFromEmpAndRelatedResponse", Namespace="http://rentacar.org/", Order=0)]
        public DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponseBody Body;
        
        public GetMetaDataFromEmpAndRelatedResponse() {
        }
        
        public GetMetaDataFromEmpAndRelatedResponse(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://rentacar.org/")]
    public partial class GetMetaDataFromEmpAndRelatedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMetaDataFromEmpAndRelatedResult;
        
        public GetMetaDataFromEmpAndRelatedResponseBody() {
        }
        
        public GetMetaDataFromEmpAndRelatedResponseBody(string GetMetaDataFromEmpAndRelatedResult) {
            this.GetMetaDataFromEmpAndRelatedResult = GetMetaDataFromEmpAndRelatedResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAss6SoapChannel : DesktopApp1.Assignment6Reference.WebServiceAss6Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAss6SoapClient : System.ServiceModel.ClientBase<DesktopApp1.Assignment6Reference.WebServiceAss6Soap>, DesktopApp1.Assignment6Reference.WebServiceAss6Soap {
        
        public WebServiceAss6SoapClient() {
        }
        
        public WebServiceAss6SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAss6SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAss6SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAss6SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.HelloWorldResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.HelloWorld(DesktopApp1.Assignment6Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DesktopApp1.Assignment6Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment6Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.HelloWorldRequestBody();
            DesktopApp1.Assignment6Reference.HelloWorldResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.HelloWorldResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.HelloWorldAsync(DesktopApp1.Assignment6Reference.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.HelloWorldResponse> HelloWorldAsync() {
            DesktopApp1.Assignment6Reference.HelloWorldRequest inValue = new DesktopApp1.Assignment6Reference.HelloWorldRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.HelloWorldRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllIndexesResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllIndexes(DesktopApp1.Assignment6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexes(request);
        }
        
        public string GetAllIndexes() {
            DesktopApp1.Assignment6Reference.GetAllIndexesRequest inValue = new DesktopApp1.Assignment6Reference.GetAllIndexesRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllIndexesRequestBody();
            DesktopApp1.Assignment6Reference.GetAllIndexesResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllIndexes(inValue);
            return retVal.Body.GetAllIndexesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllIndexesResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllIndexesAsync(DesktopApp1.Assignment6Reference.GetAllIndexesRequest request) {
            return base.Channel.GetAllIndexesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllIndexesResponse> GetAllIndexesAsync() {
            DesktopApp1.Assignment6Reference.GetAllIndexesRequest inValue = new DesktopApp1.Assignment6Reference.GetAllIndexesRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllIndexesRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllIndexesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllKeysResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllKeys(DesktopApp1.Assignment6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeys(request);
        }
        
        public string GetAllKeys() {
            DesktopApp1.Assignment6Reference.GetAllKeysRequest inValue = new DesktopApp1.Assignment6Reference.GetAllKeysRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllKeysRequestBody();
            DesktopApp1.Assignment6Reference.GetAllKeysResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllKeys(inValue);
            return retVal.Body.GetAllKeysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllKeysResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllKeysAsync(DesktopApp1.Assignment6Reference.GetAllKeysRequest request) {
            return base.Channel.GetAllKeysAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllKeysResponse> GetAllKeysAsync() {
            DesktopApp1.Assignment6Reference.GetAllKeysRequest inValue = new DesktopApp1.Assignment6Reference.GetAllKeysRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllKeysRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllKeysAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTableConstraints(DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest request) {
            return base.Channel.GetAllTableConstraints(request);
        }
        
        public string GetAllTableConstraints() {
            DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest inValue = new DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequestBody();
            DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTableConstraints(inValue);
            return retVal.Body.GetAllTableConstraintsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTableConstraintsAsync(DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest request) {
            return base.Channel.GetAllTableConstraintsAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTableConstraintsResponse> GetAllTableConstraintsAsync() {
            DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest inValue = new DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTableConstraintsRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTableConstraintsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllColumnsFromEmp1(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request request) {
            return base.Channel.GetAllColumnsFromEmp1(request);
        }
        
        public string GetAllColumnsFromEmp1() {
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request inValue = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1RequestBody();
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllColumnsFromEmp1(inValue);
            return retVal.Body.GetAllColumnsFromEmp1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllColumnsFromEmp1Async(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request request) {
            return base.Channel.GetAllColumnsFromEmp1Async(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Response> GetAllColumnsFromEmp1Async() {
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request inValue = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp1RequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllColumnsFromEmp1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllColumnsFromEmp2(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request request) {
            return base.Channel.GetAllColumnsFromEmp2(request);
        }
        
        public string GetAllColumnsFromEmp2() {
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request inValue = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2RequestBody();
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllColumnsFromEmp2(inValue);
            return retVal.Body.GetAllColumnsFromEmp2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllColumnsFromEmp2Async(DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request request) {
            return base.Channel.GetAllColumnsFromEmp2Async(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Response> GetAllColumnsFromEmp2Async() {
            DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request inValue = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllColumnsFromEmp2RequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllColumnsFromEmp2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllTablesDB1Response DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTablesDB1(DesktopApp1.Assignment6Reference.GetAllTablesDB1Request request) {
            return base.Channel.GetAllTablesDB1(request);
        }
        
        public string GetAllTablesDB1() {
            DesktopApp1.Assignment6Reference.GetAllTablesDB1Request inValue = new DesktopApp1.Assignment6Reference.GetAllTablesDB1Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTablesDB1RequestBody();
            DesktopApp1.Assignment6Reference.GetAllTablesDB1Response retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTablesDB1(inValue);
            return retVal.Body.GetAllTablesDB1Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB1Response> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTablesDB1Async(DesktopApp1.Assignment6Reference.GetAllTablesDB1Request request) {
            return base.Channel.GetAllTablesDB1Async(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB1Response> GetAllTablesDB1Async() {
            DesktopApp1.Assignment6Reference.GetAllTablesDB1Request inValue = new DesktopApp1.Assignment6Reference.GetAllTablesDB1Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTablesDB1RequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTablesDB1Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetAllTablesDB2Response DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTablesDB2(DesktopApp1.Assignment6Reference.GetAllTablesDB2Request request) {
            return base.Channel.GetAllTablesDB2(request);
        }
        
        public string GetAllTablesDB2() {
            DesktopApp1.Assignment6Reference.GetAllTablesDB2Request inValue = new DesktopApp1.Assignment6Reference.GetAllTablesDB2Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTablesDB2RequestBody();
            DesktopApp1.Assignment6Reference.GetAllTablesDB2Response retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTablesDB2(inValue);
            return retVal.Body.GetAllTablesDB2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB2Response> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetAllTablesDB2Async(DesktopApp1.Assignment6Reference.GetAllTablesDB2Request request) {
            return base.Channel.GetAllTablesDB2Async(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetAllTablesDB2Response> GetAllTablesDB2Async() {
            DesktopApp1.Assignment6Reference.GetAllTablesDB2Request inValue = new DesktopApp1.Assignment6Reference.GetAllTablesDB2Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetAllTablesDB2RequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetAllTablesDB2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetNameAbsentMost(DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest request) {
            return base.Channel.GetNameAbsentMost(request);
        }
        
        public string GetNameAbsentMost() {
            DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest inValue = new DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetNameAbsentMostRequestBody();
            DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetNameAbsentMost(inValue);
            return retVal.Body.GetNameAbsentMostResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetNameAbsentMostAsync(DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest request) {
            return base.Channel.GetNameAbsentMostAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetNameAbsentMostResponse> GetNameAbsentMostAsync() {
            DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest inValue = new DesktopApp1.Assignment6Reference.GetNameAbsentMostRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetNameAbsentMostRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetNameAbsentMostAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetInfoEmpSickness2004(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request request) {
            return base.Channel.GetInfoEmpSickness2004(request);
        }
        
        public string GetInfoEmpSickness2004() {
            DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request inValue = new DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004RequestBody();
            DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetInfoEmpSickness2004(inValue);
            return retVal.Body.GetInfoEmpSickness2004Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetInfoEmpSickness2004Async(DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request request) {
            return base.Channel.GetInfoEmpSickness2004Async(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Response> GetInfoEmpSickness2004Async() {
            DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request inValue = new DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004Request();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetInfoEmpSickness2004RequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetInfoEmpSickness2004Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetInfoFromEmpAndRelatives(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest request) {
            return base.Channel.GetInfoFromEmpAndRelatives(request);
        }
        
        public string GetInfoFromEmpAndRelatives() {
            DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest inValue = new DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequestBody();
            DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetInfoFromEmpAndRelatives(inValue);
            return retVal.Body.GetInfoFromEmpAndRelativesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetInfoFromEmpAndRelativesAsync(DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest request) {
            return base.Channel.GetInfoFromEmpAndRelativesAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesResponse> GetInfoFromEmpAndRelativesAsync() {
            DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest inValue = new DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetInfoFromEmpAndRelativesRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetInfoFromEmpAndRelativesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetMetaDataFromEmpAndRelated(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest request) {
            return base.Channel.GetMetaDataFromEmpAndRelated(request);
        }
        
        public string GetMetaDataFromEmpAndRelated() {
            DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest inValue = new DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequestBody();
            DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse retVal = ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetMetaDataFromEmpAndRelated(inValue);
            return retVal.Body.GetMetaDataFromEmpAndRelatedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse> DesktopApp1.Assignment6Reference.WebServiceAss6Soap.GetMetaDataFromEmpAndRelatedAsync(DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest request) {
            return base.Channel.GetMetaDataFromEmpAndRelatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedResponse> GetMetaDataFromEmpAndRelatedAsync() {
            DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest inValue = new DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequest();
            inValue.Body = new DesktopApp1.Assignment6Reference.GetMetaDataFromEmpAndRelatedRequestBody();
            return ((DesktopApp1.Assignment6Reference.WebServiceAss6Soap)(this)).GetMetaDataFromEmpAndRelatedAsync(inValue);
        }
    }
}
